### ISSUE TITLE
WARNING: THIS FILE CONTAINS A CRYPTO MINER

### ISSUE THREAD

**Issue by SeanErn** [robertkleffner/mariohtml5#33]
DO NOT USE UNDER ANY CIRCUMSTANCE.

**Comment by TheRealDigitalMaster** [comment]
Thanks! I was wondering **why** my chromebook was shutting down automatically. I deleted the file right away.

**Comment by matthewholt1** [comment]
this dude's got balls committing a crypto miner.

**Comment by TheRealDigitalMaster** [comment]
bro i didnt make the miner i downloaded it

**Comment by matthewholt1** [comment]
the repo owner

**Comment by matthewholt1** [comment]
Looks like it's been patched up.
Commit: https://github.com/robertkleffner/mariohtml5/commit/bf8e599a1a075ca4cba3488ae90167766284ce42

**Comment by TheRealDigitalMaster** [comment]
K

**Comment by robertkleffner** [comment]
I have removed MIDIjs entirely from the master branch. The project no longer plays background music, but it never really worked that well anyway. It is likely there are better methods of doing it in the browser now anyway, and this repo is quite old now.

**Comment by SeanErn** [comment]
Okay, I'm going to close this issue because it isn't really relevant anymore.
